# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjy-2H43_hew2UPi3OVk30DUlcykByFu
"""

import heapq
import time
import tracemalloc

# 1. MANGGIL DATA DARI FILE dataset_papandayan.py YANG TADI KAMU SAVE
from dataset_papandayan import graph_papandayan, heuristic_puncak

# ==========================================
# 2. ALGORITMA UNIFORM COST SEARCH (UCS)
# ==========================================
def ucs(graph, start, goal):
    queue = [(0, start, [start])]
    visited = set()
    nodes_expanded = 0

    while queue:
        cost, current_node, path = heapq.heappop(queue)

        if current_node in visited:
            continue

        visited.add(current_node)
        nodes_expanded += 1

        if current_node == goal:
            return cost, path, nodes_expanded

        if current_node in graph:
            for neighbor, weight in graph[current_node].items():
                if neighbor not in visited:
                    heapq.heappush(queue, (cost + weight, neighbor, path + [neighbor]))

    return float('inf'), [], nodes_expanded

# ==========================================
# 3. ALGORITMA A-STAR (A*)
# ==========================================
def a_star(graph, heuristic, start, goal):
    queue = [(heuristic[start], 0, start, [start])]
    visited = set()
    nodes_expanded = 0

    while queue:
        f_cost, g_cost, current_node, path = heapq.heappop(queue)

        if current_node in visited:
            continue

        visited.add(current_node)
        nodes_expanded += 1

        if current_node == goal:
            return g_cost, path, nodes_expanded

        if current_node in graph:
            for neighbor, weight in graph[current_node].items():
                if neighbor not in visited:
                    new_g_cost = g_cost + weight
                    new_f_cost = new_g_cost + heuristic[neighbor]
                    heapq.heappush(queue, (new_f_cost, new_g_cost, neighbor, path + [neighbor]))

    return float('inf'), [], nodes_expanded

# ==========================================
# 4. FUNGSI PENGUJIAN & EKSEKUSI
# ==========================================
def run_experiment(algo_name, start, goal):
    tracemalloc.start()
    start_time = time.perf_counter()

    if algo_name == "UCS":
        cost, path, expanded = ucs(graph_papandayan, start, goal)
    else:
        cost, path, expanded = a_star(graph_papandayan, heuristic_puncak, start, goal)

    end_time = time.perf_counter()
    current, peak_memory = tracemalloc.get_traced_memory()
    tracemalloc.stop()

    exec_time_ms = (end_time - start_time) * 1000
    peak_memory_kb = peak_memory / 1024

    print(f"--- Hasil {algo_name} ---")
    print(f"Rute           : {' -> '.join(path)}")
    print(f"Jarak Total    : {cost} meter")
    print(f"Nodes Expanded : {expanded} simpul")
    print(f"Waktu Eksekusi : {exec_time_ms:.4f} ms")
    print(f"Memori Peak    : {peak_memory_kb:.2f} KB\n")

print("=== SKENARIO: MENCARI RUTE TERPENDEK KE PUNCAK ===")
run_experiment("UCS", 'Camp_David', 'Puncak')
run_experiment("A*", 'Camp_David', 'Puncak')